-- ============================================
-- 自动生成的数据同步插入脚本 (已修复列数匹配问题)
-- 基准数字 (BASE_NUMBER): 10286
-- 生成时间: 2026-04-27 15:01:55
-- 包含表: b_md_company, b_md_companydtl, b_md_companypurchaseorg, d_ct_contract_finance, d_fi_payment_body
-- ============================================

INSERT INTO `orgMaterial`.`b_md_company` (`companyid`, `companycode`, `companyname`, `nationalcode`, `nationalname`, `citycode`, `cityname`, `address`, `postcode`, `legalrepresentative`, `agent`, `depositbank`, `bankaccount`, `certificateno`, `telephone`, `fax`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`, `clientcode`, `groupcode`, `groupname`, `invoiceissuing`, `taxpayernumber`, `contactnumber`, `addressprovince`, `addresscity`, `addressarea`, `addressstreet`, `addressdetailed`, `status`, `standcurrency`) VALUES (10286001, '10286', '中电金信（南京）信息技术有限公司青海分公司', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', '800', NULL, NULL, NULL, NULL, NULL, '', '', '', '', '', '1', 'CNY');
INSERT INTO `orgMaterial`.`b_md_companydtl` (`companydtlid`, `companyid`, `companycode`, `internationvalue`, `internationcode`, `internationname`, `clientcode`, `createtime`, `createuserid`, `createusername`, `modifytime`, `modifyuserid`, `modifyusername`) VALUES (10286002, 10286001, '10286', '中电金信（南京）信息技术有限公司青海分公司', 'zh_CN', '简体中文', '800', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员');
INSERT INTO `orgMaterial`.`b_md_companypurchaseorg` (`companypurchaseorgid`, `companycode`, `companyname`, `purchasingorgcode`, `purchasingorgname`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`, `clientcode`) VALUES (10286003, '10286', '中电金信（南京）信息技术有限公司青海分公司', 'PG002', 'GMO_PC_IT', 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', '800');
INSERT INTO `orgMaterial`.`b_md_companypurchaseorg` (`companypurchaseorgid`, `companycode`, `companyname`, `purchasingorgcode`, `purchasingorgname`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`, `clientcode`) VALUES (10286004, '10286', '中电金信（南京）信息技术有限公司青海分公司', 'PG003', 'GMO_PC_BUSINESS', 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', '800');
INSERT INTO `orgMaterial`.`b_md_companypurchaseorg` (`companypurchaseorgid`, `companycode`, `companyname`, `purchasingorgcode`, `purchasingorgname`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`, `clientcode`) VALUES (10286005, '10286', '中电金信（南京）信息技术有限公司青海分公司', 'PG005', 'GMO_PC_MANAGMENT', 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', '800');
INSERT INTO `orgMaterial`.`b_md_companypurchaseorg` (`companypurchaseorgid`, `companycode`, `companyname`, `purchasingorgcode`, `purchasingorgname`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`, `clientcode`) VALUES (10286006, '10286', '中电金信（南京）信息技术有限公司青海分公司', 'PG006', 'GMO_PC_ADMIN', 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', '800');
INSERT INTO `orgMaterial`.`b_md_companypurchaseorg` (`companypurchaseorgid`, `companycode`, `companyname`, `purchasingorgcode`, `purchasingorgname`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`, `clientcode`) VALUES (10286007, '10286', '中电金信（南京）信息技术有限公司青海分公司', 'PG007', 'GMO_PC_RESOURCES', 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', '800');
INSERT INTO `orgMaterial`.`b_md_companypurchaseorg` (`companypurchaseorgid`, `companycode`, `companyname`, `purchasingorgcode`, `purchasingorgname`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`, `clientcode`) VALUES (10286008, '10286', '中电金信（南京）信息技术有限公司青海分公司', 'PG0015', 'GMO_PC_FUNCTION', 1, '超级管理员', '2026-04-27 15:01:55', 1, '超级管理员', '2026-04-27 15:01:55', '800');
INSERT INTO `srm`.`d_ct_contract_finance` (`lecodeid`, `companycode`, `companyname`, `shortname`, `chinesename`, `englishname`, `currency`, `auditorid`, `auditor`, `contractmanagerid`, `contractmanager`, `contractfinvpid`, `contractfinvp`, `createTime`, `createuserid`, `createusername`, `modifyTime`, `modifyuserid`, `modifyusername`, `clientcode`, `remark`, `filegroupid`) VALUES ('10286', '10286', '中电金信（南京）信息技术有限公司青海分公司', '1028青海分', '中电金信（南京）信息技术有限公司青海分公司', '中电金信（南京）信息技术有限公司青海分公司', 'CNY', NULL, NULL, 'P0066470', '王雪琳', 'P0066470', '王雪琳', '2026-04-27 15:01:55', NULL, NULL, '2026-04-27 15:01:55', NULL, NULL, '800', NULL, NULL);
INSERT INTO `srm`.`d_ct_business_contract_finance` (`lecodeid`, `companycode`, `companyname`, `shortname`, `chinesename`, `englishname`, `currency`, `auditorid`, `auditor`, `contractmanagerid`, `contractmanager`, `contractfinvpid`, `contractfinvp`, `createTime`, `createuserid`, `createusername`, `modifyTime`, `modifyuserid`, `modifyusername`, `clientcode`, `remark`, `filegroupid`) VALUES ('10286', '10286', '中电金信（南京）信息技术有限公司青海分公司', '1028青海分', '中电金信（南京）信息技术有限公司青海分公司', '中电金信（南京）信息技术有限公司青海分公司', 'CNY', NULL, NULL, 'P0066470', '王雪琳', 'P0066470', '王雪琳', '2026-04-27 15:01:55', NULL, NULL, '2026-04-27 15:01:55', NULL, NULL, '800', NULL, NULL);
INSERT INTO `srm`.`d_fi_payment_body` (`payment_body_id`, `payment_body_code`, `payment_body_name`, `createuserid`, `createusername`, `createtime`, `modifyuserid`, `modifyusername`, `modifytime`) VALUES (10286009, '10286', '中电金信（南京）信息技术有限公司青海分公司', NULL, NULL, NULL, NULL, NULL, NULL);